apiVersion: s3.aws.upbound.io/v1beta1
kind: Bucket
metadata:
  annotations:
    crossplane.io/external-name: ${Rand.RFC1123Subdomain}
    meta.upbound.io/example-id: s3/v1beta1/bucket
  labels:
    testing.upbound.io/example-name: b
  name: bucket-test
spec:
  forProvider:
    region: us-west-1
    tags:
      Environment: Dev
      Name: test-bucket
  providerConfigRef:
    name: default.bucket-test
